name: Deployment pipeline

on:
  push:
    branches:
     - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs: 
  simple_deployment_pipeline: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: lint 
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Discord Webhook Notify Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ success() }}
        with:
            severity: info
            description: 'to https://full-stack-open-pokedex-461v.onrender.com by ${{ github.event.head_commit.author.name}}' 
            footer: 'Severity: Informational' 
            text: A new version of Pokedex deployed
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord Webhook Notify Error
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with:
            severity: error
            description: Commit
            details: '${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.name }} broke the build :('
            footer: 'Severity: Error' 
            text: Build failed
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
